### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by KupSeRower** [MatGawron/Tutorial#3]
Mamy problem z zadaniem mianowicie nie umiemy w setery i gettery oraz property. Nie wiemy jak sie zabrac za wyswietlanie planszy, czyli guzików w view.

**Comment by majkelx** [comment]
O setterach i getterach napisałem wam tutaj:
https://medium.com/@majkelxx/properties-in-python-8f592c675fa5

**Comment by majkelx** [comment]
Starajcie się zrobić tutorial taki jak jest najpierw
